# Generated by Django 3.2.7 on 2021-09-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('meal_period', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], max_length=1)),
                ('food_class', models.CharField(choices=[('N', 'Native'), ('P', 'Popular')], max_length=1)),
                ('image', models.ImageField(upload_to='recipes')),
                ('image_caption', models.CharField(max_length=100)),
                ('video', models.URLField(blank=True)),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.tribe')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
