# Generated by Django 3.2.7 on 2021-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
