# Generated by Django 4.0.6 on 2022-08-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.CharField(max_length=1000, verbose_name='Your Review'),
        ),
    ]
