# Generated by Django 3.2.7 on 2021-09-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20210913_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
