# Generated by Django 3.2.7 on 2022-02-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20220101_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
    ]
