# Generated by Django 3.2.7 on 2022-02-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_alter_review_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='food_class',
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
