# Generated by Django 3.2.7 on 2022-02-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_auto_20220222_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
