# Generated by Django 3.2.7 on 2022-02-23 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_preparation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation',
        ),
    ]
