# Generated by Django 3.2.7 on 2022-02-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_remove_recipe_preparation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='video_file',
            field=models.FileField(default=1, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
