# Generated by Django 3.2.7 on 2022-02-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_recipe_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
